// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db/db.proto

package db

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LockRequest struct {
	Device               uint64   `protobuf:"varint,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockRequest) Reset()         { *m = LockRequest{} }
func (m *LockRequest) String() string { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()    {}
func (*LockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7886bedee616d896, []int{0}
}

func (m *LockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockRequest.Unmarshal(m, b)
}
func (m *LockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockRequest.Marshal(b, m, deterministic)
}
func (m *LockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockRequest.Merge(m, src)
}
func (m *LockRequest) XXX_Size() int {
	return xxx_messageInfo_LockRequest.Size(m)
}
func (m *LockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockRequest proto.InternalMessageInfo

func (m *LockRequest) GetDevice() uint64 {
	if m != nil {
		return m.Device
	}
	return 0
}

type LockResponse struct {
	LockId               uint64   `protobuf:"varint,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockResponse) Reset()         { *m = LockResponse{} }
func (m *LockResponse) String() string { return proto.CompactTextString(m) }
func (*LockResponse) ProtoMessage()    {}
func (*LockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7886bedee616d896, []int{1}
}

func (m *LockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockResponse.Unmarshal(m, b)
}
func (m *LockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockResponse.Marshal(b, m, deterministic)
}
func (m *LockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockResponse.Merge(m, src)
}
func (m *LockResponse) XXX_Size() int {
	return xxx_messageInfo_LockResponse.Size(m)
}
func (m *LockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockResponse proto.InternalMessageInfo

func (m *LockResponse) GetLockId() uint64 {
	if m != nil {
		return m.LockId
	}
	return 0
}

type UnlockRequest struct {
	Device               uint64   `protobuf:"varint,1,opt,name=device,proto3" json:"device,omitempty"`
	LockId               uint64   `protobuf:"varint,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockRequest) Reset()         { *m = UnlockRequest{} }
func (m *UnlockRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockRequest) ProtoMessage()    {}
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7886bedee616d896, []int{2}
}

func (m *UnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockRequest.Unmarshal(m, b)
}
func (m *UnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockRequest.Marshal(b, m, deterministic)
}
func (m *UnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockRequest.Merge(m, src)
}
func (m *UnlockRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockRequest.Size(m)
}
func (m *UnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockRequest proto.InternalMessageInfo

func (m *UnlockRequest) GetDevice() uint64 {
	if m != nil {
		return m.Device
	}
	return 0
}

func (m *UnlockRequest) GetLockId() uint64 {
	if m != nil {
		return m.LockId
	}
	return 0
}

type SetDataRequest struct {
	Lock                 uint64   `protobuf:"varint,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Device               uint64   `protobuf:"varint,2,opt,name=device,proto3" json:"device,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataRequest) Reset()         { *m = SetDataRequest{} }
func (m *SetDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetDataRequest) ProtoMessage()    {}
func (*SetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7886bedee616d896, []int{3}
}

func (m *SetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataRequest.Unmarshal(m, b)
}
func (m *SetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataRequest.Marshal(b, m, deterministic)
}
func (m *SetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataRequest.Merge(m, src)
}
func (m *SetDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetDataRequest.Size(m)
}
func (m *SetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataRequest proto.InternalMessageInfo

func (m *SetDataRequest) GetLock() uint64 {
	if m != nil {
		return m.Lock
	}
	return 0
}

func (m *SetDataRequest) GetDevice() uint64 {
	if m != nil {
		return m.Device
	}
	return 0
}

func (m *SetDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetDataRequest struct {
	Lock                 uint64   `protobuf:"varint,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Device               uint64   `protobuf:"varint,2,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7886bedee616d896, []int{4}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetLock() uint64 {
	if m != nil {
		return m.Lock
	}
	return 0
}

func (m *GetDataRequest) GetDevice() uint64 {
	if m != nil {
		return m.Device
	}
	return 0
}

type GetDataResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7886bedee616d896, []int{5}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*LockRequest)(nil), "db.LockRequest")
	proto.RegisterType((*LockResponse)(nil), "db.LockResponse")
	proto.RegisterType((*UnlockRequest)(nil), "db.UnlockRequest")
	proto.RegisterType((*SetDataRequest)(nil), "db.SetDataRequest")
	proto.RegisterType((*GetDataRequest)(nil), "db.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "db.GetDataResponse")
}

func init() { proto.RegisterFile("db/db.proto", fileDescriptor_7886bedee616d896) }

var fileDescriptor_7886bedee616d896 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0x5a, 0x5a, 0x78, 0x9b, 0x9b, 0x3e, 0x61, 0x8e, 0x7a, 0x19, 0x81, 0xe1, 0x40,
	0x48, 0xc1, 0x1f, 0x78, 0xf1, 0x20, 0x32, 0x19, 0x82, 0x07, 0xa9, 0x78, 0x96, 0xa6, 0x89, 0x63,
	0xac, 0x2e, 0xd5, 0x66, 0x82, 0x7f, 0xa9, 0xff, 0x8e, 0xa4, 0x69, 0x5c, 0x73, 0x51, 0xf0, 0xf6,
	0x7e, 0x7d, 0x3f, 0x2f, 0xf9, 0x3e, 0xe8, 0x72, 0x96, 0x70, 0x46, 0xcb, 0x77, 0xa9, 0x24, 0xfa,
	0x9c, 0xc5, 0x47, 0x0b, 0x29, 0x17, 0x85, 0x48, 0xea, 0x0a, 0xdb, 0xbc, 0x24, 0xe2, 0xb5, 0x54,
	0x9f, 0x66, 0x80, 0x4c, 0xa0, 0x7b, 0x2f, 0xf3, 0x55, 0x2a, 0xde, 0x36, 0xa2, 0x52, 0x38, 0x84,
	0x90, 0x8b, 0x8f, 0x65, 0x2e, 0x46, 0xde, 0xd8, 0x9b, 0x06, 0x69, 0x93, 0x91, 0x63, 0xe8, 0x99,
	0xb1, 0xaa, 0x94, 0xeb, 0x4a, 0xe0, 0x21, 0x44, 0x85, 0xcc, 0x57, 0xcf, 0x4b, 0x6e, 0x07, 0x75,
	0x7a, 0xc7, 0xc9, 0x35, 0xec, 0x3e, 0xad, 0x8b, 0xbf, 0x89, 0x6d, 0x82, 0xef, 0x10, 0x1e, 0xa0,
	0xff, 0x28, 0xd4, 0x2c, 0x53, 0x99, 0x45, 0x20, 0x04, 0xba, 0xd7, 0x00, 0xea, 0xb8, 0x85, 0xf5,
	0x1d, 0x2c, 0x42, 0xc0, 0x33, 0x95, 0x8d, 0x76, 0xc6, 0xde, 0xb4, 0x97, 0xd6, 0x31, 0xb9, 0x82,
	0xfe, 0xfc, 0xdf, 0x44, 0x32, 0x81, 0xc1, 0x8f, 0xba, 0xf9, 0xbd, 0x5d, 0xe2, 0x6d, 0x97, 0x9c,
	0x7e, 0x79, 0xe0, 0xcf, 0x6e, 0xf0, 0x04, 0x02, 0x6d, 0x14, 0x0e, 0x28, 0x67, 0xb4, 0xe5, 0x6c,
	0xbc, 0xb7, 0x2d, 0x18, 0x0a, 0xe9, 0xe0, 0x05, 0x84, 0xc6, 0x2c, 0xdc, 0xd7, 0x5d, 0xc7, 0xb8,
	0x78, 0x48, 0xcd, 0xdd, 0xa8, 0xbd, 0x1b, 0xbd, 0xd5, 0x77, 0x23, 0x1d, 0xbc, 0x84, 0xa8, 0x71,
	0x08, 0x51, 0xeb, 0x5c, 0xbb, 0x7e, 0x11, 0x9e, 0x43, 0x34, 0x6f, 0x0b, 0x5d, 0x57, 0xe2, 0x03,
	0xa7, 0x66, 0x5f, 0xc9, 0xc2, 0x9a, 0x73, 0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xdb, 0xa0,
	0x3b, 0x59, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBClient is the client API for DB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBClient interface {
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, "/db.DB/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/db.DB/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/db.DB/SetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/db.DB/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBServer is the server API for DB service.
type DBServer interface {
	Lock(context.Context, *LockRequest) (*LockResponse, error)
	Unlock(context.Context, *UnlockRequest) (*empty.Empty, error)
	SetData(context.Context, *SetDataRequest) (*empty.Empty, error)
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
}

// UnimplementedDBServer can be embedded to have forward compatible implementations.
type UnimplementedDBServer struct {
}

func (*UnimplementedDBServer) Lock(ctx context.Context, req *LockRequest) (*LockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedDBServer) Unlock(ctx context.Context, req *UnlockRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedDBServer) SetData(ctx context.Context, req *SetDataRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetData not implemented")
}
func (*UnimplementedDBServer) GetData(ctx context.Context, req *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_SetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).SetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/SetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).SetData(ctx, req.(*SetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "db.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _DB_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _DB_Unlock_Handler,
		},
		{
			MethodName: "SetData",
			Handler:    _DB_SetData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _DB_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db/db.proto",
}
